### ISSUE TITLE
Add support for vertical card flip.

### ISSUE THREAD

**Issue by AaronCCWong** [AaronCCWong/react-card-flip#1]
Add css to allow for vertical card flip.

**Comment by thiagodebastos** [comment]
I'll have a look into this for you tomorrow if I get some time.

**Comment by igorkamyshev** [comment]
Is this issue still relevant?

**Comment by AaronCCWong** [comment]
@igorkamyshev It would be a nice to have but not urgent.

**Comment by igorkamyshev** [comment]
@AaronCCWong Ok. I will try to implement it.

**Comment by igorkamyshev** [comment]
@AaronCCWong sorry. I tried to solve this problem, but I could not. I apologize for the long time there.

**Comment by AaronCCWong** [comment]
@igorkamyshev Not a problem. I haven't had any time to think about this myself either.

**Comment by fizcoder** [comment]
This would be awesome
