### ISSUE TITLE
ReactCardFlip causing incorrect sizing

### ISSUE THREAD

**Issue by mjsevilla** [AaronCCWong/react-card-flip#10]
Here's what my first card looks like before implementing RCF:
<img width="1440" alt="screen shot 2017-05-22 at 11 23 31 am" src="https://cloud.githubusercontent.com/assets/7141345/26323234/f13f9980-3ee2-11e7-9ff3-9cfc770e549c.png">

And here's how it looks after implementing RCF:
<img width="1440" alt="screen shot 2017-05-22 at 11 23 49 am" src="https://cloud.githubusercontent.com/assets/7141345/26323269/0ce7e89a-3ee3-11e7-9b9d-8cf038e55813.png">

Material-ui's `Card` components are supposed to take the height and width of the components inside. But for some reason, when implementing RCF, it's forcing the Card component to take the size of it's relative Cards in a GridList?

**Comment by mjsevilla** [comment]
Relevant code:

    <GridList
              className="grid list"
              cellHeight="auto"
              style={styles.gridList}
              cols={3}
            >
              <GridTile>
                <ReactCardFlip isFlipped={this.state.isFlipped}>
                  <Card key="front">
                    <CardHeader
                      title="Devices in Use"
                      subtitle="Subtitle"
                    />
                    <PieChart width={800} height={400}>
                      <Pie
                        data={deviceData}
                        cx={225}
                        cy={200}
                        innerRadius={60}
                        outerRadius={100}
                        fill="#8884d8"
                        paddingAngle={5}
                      >
                      	{
                        	deviceData.map((entry, index) => <Cell fill={COLORS[index % COLORS.length]}/>)
                        }
                      </Pie>
                      <Tooltip />
                    </PieChart>
                    <CardActions>
                      <RaisedButton label="More info" onTouchTap={this.handleClick} />
                    </CardActions>
                  </Card>
                  <Card className="back">
                    <CardHeader
                      title="Back"
                      subtitle="Subtitle"
                    />
                    <PieChart width={800} height={400}>
                      <Pie
                        data={deviceData}
                        cx={225}
                        cy={200}
                        innerRadius={60}
                        outerRadius={100}
                        fill="#8884d8"
                        paddingAngle={5}
                      >
                      	{
                        	deviceData.map((entry, index) => <Cell fill={COLORS[index % COLORS.length]}/>)
                        }
                      </Pie>
                      <Tooltip />
                    </PieChart>
                    <CardActions>
                      <RaisedButton label="More info" onTouchTap={this.handleClick} />
                    </CardActions>
                  </Card>
                </ReactCardFlip>
              </GridTile
              ...
            </GridList>

**Comment by AaronCCWong** [comment]
Have you tried changing the second card to have `key="back"`.

**Comment by mjsevilla** [comment]
Yeah, changing `className` to `key` yields the same result. For some reason though, the `react-card-flip` div has a 0 height? Setting the height of the `card` component changes nothing.

![screen shot 2017-05-23 at 10 18 08 am](https://cloud.githubusercontent.com/assets/7141345/26366771/25ad39b6-3fa1-11e7-9474-6afaf541bff3.png)

**Comment by AaronCCWong** [comment]
Can you set up a jsfiddle for me to look at?

**Comment by AaronCCWong** [comment]
The reason the `react-card-flip` div has height 0 is because the divs `react-card-front` and `react-card-back` are positioned absolute.

**Comment by mjsevilla** [comment]
My apologies, I'm trying to figure out how to get my code running in jsfiddle right now. I'm completely new to react and I'm learning as I'm going.

**Comment by AaronCCWong** [comment]
What about the repo? Is it public? If it is I can look there instead.

**Comment by mjsevilla** [comment]
https://github.com/mjsevilla/dashboard.git

Here you go

**Comment by AaronCCWong** [comment]
The problem here is the `GridTile` component. If you give that a height of 400px it'll fix the problem. This occurs because `ReactCardFlip` depends on position absolute to be able to create the appearance of a single card flipping back and forth. When an element is positioned absolute, it no longer takes up space in the DOM so your `GridTile` component doesn't know that it needs to be 400px.

**Comment by mjsevilla** [comment]
Thank you! It's working now. Big thanks especially since it wasn't a bug related to RCF and just my own doing. Is there a way to make the card's height adapt to the contents within the card instead of explicitly stating the size?

**Comment by AaronCCWong** [comment]
Having the card adapt automatically to the contents of the card is actually an interesting question because for that to be possible, we would actually need to remove position absolute which would break the functionality of `ReactCardFlip`. 

On your question about filling up the space with GridList and GridTiles maybe flexbox could be of some help? Unfortunately I have never used those components so I am not too familiar with them.

Do let me know if you think you have a good solution to the first question though. Closing this issue. Feel free to open up another issue if you have any more problems.
