### ISSUE TITLE
Scroll not working on Safari

### ISSUE THREAD

**Issue by Serbiaguy96** [AaronCCWong/react-card-flip#120]
When one of the cards (back or front) has overflow: auto or scroll then scrolling works perfectly on Chrome. But in Safari behave like overflow: hidden. I am not sure for now what is causing this problem, but might be problem with perspective.

Can yoy guys check it out pleas?

**Comment by yangchristina** [comment]
This worked for me
```jsx
<ReactCardFlip
    cardStyles={{
        back: {
            zIndex: isFlipped ? '2' : '1',
            transform: backRotateY
        },
    }}
    isFlipped={isFlipped}
    flipDirection="horizontal"
>
    ...
</ReactCardFlip>
```
