### ISSUE TITLE
Not working on react 16

### ISSUE THREAD

**Issue by pablonm3** [AaronCCWong/react-card-flip#22]
Hello, I'm trying a super simple example and, nothing is rendered in the screen, also no errors are logged in the console
Here is the snippet, note that if I replace the "CardFlip" tag with a span, the element is rendered as expected: 
```

...
import CardFlip from 'react-card-flip';
function Component(props){
return <CardFlip isFlipped={true}>
                    <div key="front">
                    <img
                            src="//img.buzzfeed.com/buzzfeed-static/static/2014-04/enhanced/webdr06/4/16/enhanced-11136-1396643149-13.jpg?no-auto"
                        />
                        <button>Click to flip</button>
                    </div>
                    <div key="back">
                    <img
                            src="//img.buzzfeed.com/buzzfeed-static/static/2014-04/enhanced/webdr06/4/16/enhanced-11136-1396643149-13.jpg?no-auto"
                        />
                        <button>Click to flip</button>
                    </div>
                </CardFlip>

}
...

```
I'm using react V16.2.0

**Comment by pablonm3** [comment]
I suspect it could be a css issue, since I heard this components uses absolute positioning

**Comment by AaronCCWong** [comment]
Is there a public repo I can look at? The example you provide works for me.

**Comment by pablonm3** [comment]
Please check the render method at:
https://github.com/flashcardx/web/blob/card-flippable/src/components/flashcard.jsx
if i replace your tag with a simple span it works, I'm pretty sure this has to be with the absolute position of your component, is it posible to override this behaviour?

**Comment by AaronCCWong** [comment]
I copy and pasted your code for into your footer and it works properly.

**Comment by pablonm3** [comment]
Got it!, thanks for the support!
