### ISSUE TITLE
dependency tree includes upath@1.0.0 which breaks npm install for recent NodeJS versions

### ISSUE THREAD

**Issue by danielweck** [AaronCCWong/react-card-flip#27]
Trying `rm -rf node_modules && rm package-lock.json && npm install` in my project:

```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for upath@1.0.0: wanted: {"node":">=0.10 <=7"} (current: {"node":"9.5.0","npm":"5.6.0"})
npm ERR! notsup Not compatible with your version of node/npm: upath@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: upath@1.0.0
npm ERR! notsup Required: {"node":">=0.10 <=7"}
npm ERR! notsup Actual:   {"npm":"5.6.0","node":"9.5.0"}
```
Ouch! It turns out `react-card-flip` currently depends on `upath@1.0.0` (instead of a more recent version). See:

`npm install --global npm-remote-ls && npm-remote-ls react-card-flip@0.2.1 | grep -i upath`

...and indeed in your `yarn.lock`:

https://github.com/AaronCCWong/react-card-flip/blob/master/yarn.lock#L1499

It seems that `chokidar` needs to be updated to the latest version `2.0.1` to fix this problem:

https://github.com/paulmillr/chokidar/pull/679/files

Meanwhile, I am just going to revert back to a previous version of `react-card-flip`.

Thanks for looking into this!

**Comment by danielweck** [comment]
Wait, `chokidar` version 2.0.2 has not been released yet! Sorry. Closing this issue now.

**Comment by AaronCCWong** [comment]
@danielweck Thanks for pointing this out! I will keep this in mind and upgrade when they release.

**Comment by danielweck** [comment]
I posted here:
https://github.com/paulmillr/chokidar/pull/679#issuecomment-365436112

**Comment by danielweck** [comment]
Damn, `webpack-dev-server` is affected too:

`npm-remote-ls webpack-dev-server@2.11.1 | grep -i upath`
```
   │  ├─ upath@1.0.0
```

:(

**Comment by danielweck** [comment]
Update: apparently `--engine-strict` can default to true in some cases!
`mkdir ChokidarTest && cd ChokidarTest && npm init --yes && npm install chokidar --engine-strict=false`
=> okay.
By forcing `--engine-strict` to false, I should be able to get around this issue.

**Comment by danielweck** [comment]
Chokidar v2.0.2 is out, fixes the `npm install --engine-strict=true` issue. See:
https://github.com/paulmillr/chokidar/issues/681#issuecomment-365670322
