### ISSUE TITLE
Text Overflow Impacting Visibility

### ISSUE THREAD

**Issue by aliogaili** [AaronCCWong/react-card-flip#30]
I noticed that if I add a text with fixed height and overflowY:scroll, the back will show even if 
it's not flipped. 

<img width="312" alt="screen shot 2018-03-19 at 3 29 50 pm" src="https://user-images.githubusercontent.com/1675307/37593147-6b449c82-2b8a-11e8-948a-683ef3efb215.png">

I'm trying to squeeze a long text in a small card so I'm using overflowY.

Thanks

**Comment by rhazegh** [comment]
I think issue #31 is related to this issue. Similar behaviour.

**Comment by AaronCCWong** [comment]
@aliogaili This may be help solve your issue:

https://github.com/AaronCCWong/react-card-flip/issues/31#issuecomment-389934390

Since this issue has become stale I will close this. If that does not solve the problem please create another issue.

**Comment by pushkardeshmukh1992** [comment]
`overflow: auto` breaks the flip. Any resolution for this?
