### ISSUE TITLE
How do I override the css?

### ISSUE THREAD

**Issue by simodroussi** [AaronCCWong/react-card-flip#35]
I have an image inside the flipper. I want to change the style of the react-card-front and react-card-back. I want the position to be relative instead of absolute. Is there a way to do that?

**Comment by simodroussi** [comment]
No one?

**Comment by AaronCCWong** [comment]
@simodroussi Sorry for taking so long to respond. You can definitely change the style to use relative by overwriting the position of `react-card-front` and `react-card-back` but be aware that this can cause issues with the way the card takes up space.

Please refer to this comment for more information:
https://github.com/AaronCCWong/react-card-flip/issues/7#issuecomment-302832188
