### ISSUE TITLE
Issue with other components - causing overlap

### ISSUE THREAD

**Issue by fizcoder** [AaronCCWong/react-card-flip#40]
I'm experiencing an issue with other components causing an overlap for example if I have a dropdown using bootstrap, it gets overlapped with a near by component. See screenshot below:

![Overlap issue](https://user-images.githubusercontent.com/5448149/53561727-8913be00-3b47-11e9-88a4-5d660ca6f779.png)

The issue seems to be with the `.react-card-flip` and `.react-card-flipper` because when I disable the following in .react-card-flip:

```
perspective: 1000px;
transform-style: preserve-3d;
```

and disable the following in .react-card-flipper:

```
transform-style: preserve-3d;
```

It behaves fine. See screenshot below:

![dropdown showing fine](https://user-images.githubusercontent.com/5448149/53561956-135c2200-3b48-11e9-99ed-76d70b90cca6.png)

Do you know how to resolve this?

**Comment by fizcoder** [comment]
Any update on this? Thanks.

**Comment by fizcoder** [comment]
*bump*

**Comment by sbardian** [comment]
@fizcoder I'm willing to look around and see what I see.  Do you have a codesandbox.io to show this happening?  Would speed things up if you had a working example of the issue.

**Comment by sbardian** [comment]
@fizcoder this seems to be an issue with the react flip cards having a separate context stack because of their transitions/animations.  If possible one solution I can see at this point is to move the popup elements (date picker/etc) as siblings to the flip cards.  This causes other issues with positioning the popups though.  I will continue to look into it for a better solution.

**Comment by sbardian** [comment]
@fizcoder I have submitted a PR that should help with your issue.   You will want to apply a reversed z-index layout to your flip cards.  Last card low (1) first card high (1000) type of setup.  This will allow your child elements (popups) of cards above to overlap (not fall behind) other flip cards below it.  We will see what @AaronCCWong thinks of it, works fine in my testing.

**Comment by zach-luman** [comment]
Look forward to merging @fizcoder 's PR.

**Comment by zach-luman** [comment]
any update here?

**Comment by sbardian** [comment]
bump @AaronCCWong

**Comment by zach-luman** [comment]
@sbardian It seems like this plugin is not being maintained anymore.
Could you please guide me on how to apply your updates on my local?

**Comment by AaronCCWong** [comment]
Sorry for the delay. Will take a look by eod.

**Comment by sbardian** [comment]
Thanks @AaronCCWong !

**Comment by zach-luman** [comment]
@sbardian @AaronCCWong 
Setting 1000~0 as cardZIndex props to continuous flip cards doesn't resolve the issue yet.

**Comment by sbardian** [comment]
This worked with my testing.  Do you have a codesandbox or some code to show me how you are using it?

**Comment by zach-luman** [comment]
`this.state.vehicles.map((auction, index) => (
    <ReactCardFlip isFlipped={this.state.viewMode} flipDirection="vertical" cardZIndex={1000-index}>
))`

**Comment by zach-luman** [comment]
@sbardian any idea?

**Comment by sbardian** [comment]
hmm   not sure.  seems fine here, threw this together really quick.  

https://codesandbox.io/s/3y7x40m871

**Comment by sbardian** [comment]
> http://prntscr.com/n39zjr
> @sbardian any idea?

Probably already did this, but . . . css change sooo CTRL+F5?  or Shift+Command+R ?   stupid but . .  maybe ?

**Comment by zach-luman** [comment]
https://codesandbox.io/embed/53only1j54
@sbardian Even without cardZIndex props in your code, it works as expected.
How is it possible?

**Comment by sbardian** [comment]
@zach-luman I started checking other browsers, are you on chrome?  You are right, this doesn't seem to be working on chrome from what I'm seeing at this point.  Let me review further.

**Comment by sbardian** [comment]
@zach-luman in Chrome open up dev tools and add `position: relative;` to the react-card-flip class.  This seems to do the trick in chrome, but I will have to test further before pushing another PR.

**Comment by sbardian** [comment]
Yup from what I see setting position: relative on the class `react-card-flip` seems to do the trick to fix this in `Chrome` and doesn't seem to break `FireFox`.  #42 would handle this as you could pass this to the container, or I could push another PR to add this to the container.  @AaronCCWong do you have a preference on this one?  Adding `position: relative` is more specific than just spreading styles across the container.  Spreading styles across the container does allow users freedom, but opens them up to breaking functionality, but I guess that would be on them?   I leave it to you, let me know if you want a PR or if you will pursue #42

**Comment by AaronCCWong** [comment]
@sbardian I will play around with `position: relative` to see if it affects the functionality. Using relative positioning has caused problems in the past.

**Comment by satyasonu** [comment]
Can anyone please let me know how to overcome this overlapping issue by adding position: relative here? 
using login page inside this component<ReactCardFlip ></ReactCardFlip > and causing overlap to sidebar in mobile view.
![image](https://github.com/AaronCCWong/react-card-flip/assets/64128421/37275945-3095-49b6-9382-c48079369b86)
