### ISSUE TITLE
Need Support For SSR: Breaks Gatsby Build 

### ISSUE THREAD

**Issue by Skillz4Killz** [AaronCCWong/react-card-flip#43]
When building the website with `gatsby build` in a GatsbyJS project, this module breaks the build because it doesnt support Server Side Rendering.

![image](https://user-images.githubusercontent.com/23035000/56401330-422c7580-6226-11e9-8ce8-5d6f0bb08972.png)

**Comment by ammarlakis** [comment]
I've created PR #44  for this, it's a Webpack configuration option.

**Comment by AaronCCWong** [comment]
@ammarlakis I will take a look and get it merged by EOD. Thanks!
