### ISSUE TITLE
Large bundle because of dependencies

### ISSUE THREAD

**Issue by Paso** [AaronCCWong/react-card-flip#45]
The minified bundle is 14kB while the raw source is only 4kB, this is probably because some dependencies are included in the bundle. It should be up to the user of the package to install the required dependencies so that they are not duplicated in the requiring application. To resolve this the package.json should switch to peerDependencies instead of dependencies.

**Comment by AaronCCWong** [comment]
Agreed. I'll accept a PR from you or I can make the update later this week or early next week.

**Comment by Paso** [comment]
Awesome! Thank you!
