### ISSUE TITLE
FrontComponent

### ISSUE THREAD

**Issue by lotusms** [AaronCCWong/react-card-flip#5]
I noticed you have a FrontComponent element in your code, When I use your code it gives an error that it is undefined. I thought it would be built in but doesn't seem like it. Where is this coming from? I didn't find it in your GitHub source either.

The transform: rotateY(180deg); is not rendering and I'm thinking it might be because of this. It is the only thing different between your code and mine.

**Comment by AaronCCWong** [comment]
When I said `FrontComponent` and `BackComponent` I meant it as the component you want to be shown in the front. If you look [here](https://github.com/AaronCCWong/react-card-flip/blob/master/example/src/example.js) you can see a better example of it on line 43. 

I will update my example in the docs to be less confusing.

**Comment by lotusms** [comment]
Ah! I see, in that case, we have the same code. What event toggles the transform: rotateY(180deg); Becasue it is not showing when I call the function onClick? How are you handling that toggle event?

**Comment by AaronCCWong** [comment]
`ReactCardFlip` handles the rotate through a boolean value that you can pass to it via the  `isFlipped` prop. If you show me with the component where you are trying to use `ReactCardFlip` I may be able to better pinpoint the problem.

Thank you for using `ReactCardFlip`.

**Comment by lotusms** [comment]
Thank you. Here is the Component (Slimmed a little of course)

    `import React from 'react';
     import { connect } from 'react-redux';
     import classnames from 'classnames';

     //other imports here for material-ui and other dependencies

     class DashboardContent extends React.Component {
	       constructor(props) {
	          super(props);
	           this.state = {
		         isMediaFlipped:false,
	           };
               this.handleMediaFlip = this.handleMediaFlip.bind(this);
            }

            handleMediaFlip(e) {
	            e.preventDefault();
	            this.setState({ isMediaFlipped: !this.state.isMediaFlipped });
            }
            render() {
               const Statusboxes = () => (
                     <Row className='flip-card-container'>
                              <Col xs={12} sm={4} md={2} className='flip-card'>
					<ReactCardFlip isFlipped={this.state.isMediaFlipped} className='flip-card-container'>
				                <div key="front">
						        <div className="box">
							        <Row between="xs" className="box-top">
								        <span className="box-title">Media</span>
								        <IconMenu iconButtonElement={<IconButton><i className="material-icons">more_vert</i></IconButton>}
					            		               onChange={this.handleChange}
					            		               anchorOrigin={{horizontal: 'right', vertical: 'bottom'}}
					            		               targetOrigin={{horizontal: 'right', vertical: 'top'}}
					            		               menuStyle={{minWidth: '150px'}}>
					            		               <MenuItem className="menu-item"
					              			               primaryText="Details"
									               onClick={this.handleMediaFlip} //onClick event instead of button
					              			               style={{fontSize: '14px', lineHeight: '48px'}}/>
			            				               <MenuItem  className="menu-item"
									               primaryText="Refresh"
									               style={{fontSize: '14px', lineHeight: '48px'}}/>
			          				        </IconMenu>
							        </Row>
							        <Col xs={12} className="box-info">
								        The front
							        </Col>
						        </div>
				                </div>

				                <div key="back">
						        <Col xs={12} className="box">
							        <Row end="xs" className="box-top">
								        <i className="material-icons" onClick={this.handleMediaFlip}>close</i>
							        </Row>
							        <Col xs={12} className="box-info">
								        The back
							        </Col>
						        </Col>
				                </div>
			      	        </ReactCardFlip>
			        </Col>
                        </Row>
                );

                return (
                     //Some stuff here
                      <Statusboxes />
                     //More stuff here
                );
           };
      }
     `

I had to modify the CSS for styling purposes as well as Material UI layout specifics but nothing in the SCSS refers to any CSS transform, animation, display manipulation (i.e opacity, or visible, etc)

The Row, Col, and other tags you see render as divs

Hope it helps

**Comment by lotusms** [comment]
I think if the key="front" can be manipulated to toggle a "flip/unflip" class(es) it would be outstanding! That way we can control the flip amount by overwriting the SCSS.

**Comment by AaronCCWong** [comment]
Ah. I see the problem here.

So the way the flip/unflip class currently works is it has a class that checks to see if `this.state. isMediaFlipped` is `true` or `false`.

In your component, we can see that `this.state.isMediaFlipped` is being sent in properly and the card even flips. The problem here is we don't see the flipping animation. The tricky part here is that the animation is actually happening. It is just being hidden by React. By defining `Statusboxes` within that render component you are effectively telling React to re-render `Statusboxes` every time the state of `DashboardContent` updates. 

Try this:

```javascript
import React from 'react';
 import { connect } from 'react-redux';
 import classnames from 'classnames';
 import ReactCardFlip from 'react-card-flip';

 //other imports here for material-ui and other dependencies

 class DashboardContent extends React.Component {
        render() {
            return (
                 //Some stuff here
                  <Statusboxes />
                 //More stuff here
            );
       };
  }

 class Statusboxes extends React.Component {
                constructor(props) {
          super(props);
           this.state = {
	         isMediaFlipped:false,
           };
           this.handleMediaFlip = this.handleMediaFlip.bind(this);
        }

        handleMediaFlip(e) {
            e.preventDefault();
            this.setState({ isMediaFlipped: !this.state.isMediaFlipped });
        }

        render() {
             return (
                  <Row className='flip-card-container'>
                          <Col xs={12} sm={4} md={2} className='flip-card'>
				<ReactCardFlip isFlipped={this.state.isMediaFlipped} className='flip-card-container'>
			                <div key="front">
					        <div className="box">
						        <Row between="xs" className="box-top">
							        <span className="box-title">Media</span>
							        <IconMenu iconButtonElement={<IconButton><i className="material-icons">more_vert</i></IconButton>}
				            		               onChange={this.handleChange}
				            		               anchorOrigin={{horizontal: 'right', vertical: 'bottom'}}
				            		               targetOrigin={{horizontal: 'right', vertical: 'top'}}
				            		               menuStyle={{minWidth: '150px'}}>
				            		               <MenuItem className="menu-item"
				              			               primaryText="Details"
								               onClick={this.handleMediaFlip} //onClick event instead of button
				              			               style={{fontSize: '14px', lineHeight: '48px'}}/>
		            				               <MenuItem  className="menu-item"
								               primaryText="Refresh"
								               style={{fontSize: '14px', lineHeight: '48px'}}/>
		          				        </IconMenu>
						        </Row>
						        <Col xs={12} className="box-info">
							        The front
						        </Col>
					        </div>
			                </div>

			                <div key="back">
					        <Col xs={12} className="box">
						        <Row end="xs" className="box-top">
							        <i className="material-icons" onClick={this.handleMediaFlip}>close</i>
						        </Row>
						        <Col xs={12} className="box-info">
							        The back
						        </Col>
					        </Col>
			                </div>
		      	        </ReactCardFlip>
		        </Col>
                    </Row>
            );
       }
}
```

**Comment by lotusms** [comment]
Outstanding! It works! Thanks man. This can be closed now :)
