### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by BlackFenix2** [AaronCCWong/react-card-flip#51]
Just a discussion thread for my eventual PR to add typescript support for this app. i can start by adding type definitions and go further by writing everything in typescript vs javascript. this would remove the need for the prop-types peer dependency.

**Comment by BlackFenix2** [comment]
i added my PR for Typescript here: https://github.com/AaronCCWong/react-card-flip/pull/52

**Comment by jctan** [comment]
would ReactCardFlip.tsx need to convert to ts for consistency?

**Comment by AaronCCWong** [comment]
`ReactCardFlip.tsx` is already TypeScript. Unless you mean the extension in which case I believe `.tsx` is the better extension as it makes clear that this file contains JSX.
