### ISSUE TITLE
Missing typescript types

### ISSUE THREAD

**Issue by jhrabows** [AaronCCWong/react-card-flip#55]
When I import this library in my typescript project and try to build it I get a message: ReactCardFlip.d.ts (2,39): Cannot find name ReactFlipCardProps. I see that this name is defined in the github source but it is not in the node_modules folder.

**Comment by AaronCCWong** [comment]
Thanks for reaching out!

I created a small TypeScript app using create-react-app and am not able to reproduce this issue. Can you provide a code snippet that has this issue?

**Comment by jhrabows** [comment]
Hi Aron,
I created a project using CRA and copy/pasted sample from the readme file. Indeed had no issue. However, this happened because the CRA default value for skipLibCheck in tsconfig.json was set to 'true'. As soon as I changed that value to false I got this error:

```
TypeScript error in C:/Users/janhr/Desktop/react-typescript/my-app/node_modules/react-card-flip/lib/ReactCardFlip.d.ts(2,39):
Cannot find name 'ReactFlipCardProps'.  TS2304

    1 | import * as React from 'react';
  > 2 | declare const ReactCardFlip: React.FC<ReactFlipCardProps>;
      |                                       ^
    3 | export default ReactCardFlip;
    4 |
```

Hope this helps

**Comment by AaronCCWong** [comment]
Commit f9b3eb7 should fix this issue. Please reopen if it continues to occur.

**Comment by jhrabows** [comment]
looks good now
