### ISSUE TITLE
upgrade react peer dependency to v17

### ISSUE THREAD

**Issue by marcusellison** [AaronCCWong/react-card-flip#63]
Erro to install dependency in a new react app using npm 7

**Screenshot**
![zsh](https://user-images.githubusercontent.com/1753324/99158579-1e8f1280-2689-11eb-8212-f6026c7f30f6.jpg)

**To Reproduce**

1. Create a new app with create-react-app typescript template
2. Run command npm install react-card-flip --save
3. Installation will be rejected.

**Expected behavior**
Be able to install dependency with success

**Desktop:**

OS: Mac OSX
Browser Chrome
Version
- Node: v15.2.0
- NPM: 7.0.10

**Possible fix:**
Upgrade react peer dependency to v17

**Comment by LinusGeffarth** [comment]
Having the same issue...

**Comment by BarriowealthPro** [comment]
I see the pull request for this update here: https://github.com/AaronCCWong/react-card-flip/pull/64

Will it be released soon?

**Comment by AaronCCWong** [comment]
Merged and released.
