### ISSUE TITLE
Can we change the speed transition and the " door " effect transition ? [ fin solution for transition but not " door " effect ]

### ISSUE THREAD

**Issue by SSylvain1989** [AaronCCWong/react-card-flip#69]
Hello 
I would like to slow the transition , can you tell me how to do it ? 
Thanks a lot 
Best regards

**Comment by SSylvain1989** [comment]
**Find the solution :**         
```javascript
<ReactCardFlip isFlipped={isFlipped} flipDirection="horizontal" flipSpeedBackToFront={1} flipSpeedFrontToBack={1} infinite={true} >
```

#https://youtu.be/US9Hnl3Bap8
but do you know how to resolve this problem 

When the card is not " full screen " it's flip like a " door " no in the same way when the card is full screen / take all the with of the screen ? 
Thanks . 
Regards .

**Comment by AaronCCWong** [comment]
Check the container of the card. The container is used as the reference point for flipping so if the container of the card that is doing the flipping is larger than the card itself the card will appear to not flip at its center.

**Comment by AaronCCWong** [comment]
Closing. Please reopen if this is still an issue.
