### ISSUE TITLE
Allow setting className for container

### ISSUE THREAD

**Issue by Nautman** [AaronCCWong/react-card-flip#70]
Hi,

I'm very glad this package exists! I would really appreciate it if was possible to add a `className` to the container, in addition to adding `containerStyles`. This would make things easier for me as I am using this component together with TailwindCSS. 

This is the line that would need changing.

https://github.com/AaronCCWong/react-card-flip/blob/8ac78395051da6b8e1aa56488c3988bbe3579972/src/ReactCardFlip.tsx#L93

**Comment by florianGierlichs** [comment]
A custom className maybe would be even better, so you could use multiple containers with different styling

**Comment by AaronCCWong** [comment]
Will happily accept a PR for this. Otherwise, I will try to get to it in a few days.

**Comment by AaronCCWong** [comment]
https://github.com/AaronCCWong/react-card-flip/commit/89ec73e04aee19fba9c11f6a0475ad3b65953bfb

**Comment by Nautman** [comment]
Seems like a neat implementation, thanks!
