### ISSUE TITLE
preserve-3d is causing issues in Chrome v94.x

### ISSUE THREAD

**Issue by mjangir** [AaronCCWong/react-card-flip#75]
After upgrading Chrome to version 94, half of the content in react card flip is not interactive. I tried to debug it and found that disabling `transformStyle` `preserve-3d` works fine.

**Comment by AaronCCWong** [comment]
Can you provide an example of this? I am on Chrome v96 and everything here https://aaronccwong.github.io/react-card-flip/ works for me as expected.

**Comment by ashishsurya** [comment]
`persepctive : 1000px` is applying to the main container, instead there is another contianer wrapping the `front` and `back` divs

<img width="975" alt="image" src="https://github.com/AaronCCWong/react-card-flip/assets/72222785/b8ed49a2-d3ec-45cc-9099-d4b239fa9b87">

`.react-card-flip` is having the `perspective` property, instead `.react-card-flipper` must have it

**Comment by fwcd** [comment]
#125 should fix the perspective property.

**Comment by AaronCCWong** [comment]
https://github.com/AaronCCWong/react-card-flip/releases/tag/v1.2.3 includes the fix for this
