### ISSUE TITLE
part of the front card visible when flip to back card

### ISSUE THREAD

**Issue by hamed-musallam** [AaronCCWong/react-card-flip#76]
the problem comes from the z-index CSS property on the front card

front card
![image](https://user-images.githubusercontent.com/35760236/136344474-1f6d7dbb-0787-416e-aa01-652911a393c6.png)
back card
![image](https://user-images.githubusercontent.com/35760236/136344415-c71dcc9e-072a-4fe0-8524-bfa2da65faea.png)

**Comment by hamed-musallam** [comment]
@AaronCCWong 

it seems that is a bug in Chrom V94, when we have Canvas or div with the sticky position the CSS properties transform style preserve-3d and backface visibility not working as it supposes to work.

we tested the same case in Firefox and it works well without any problem.

Can you take a look at this problem at chrome?

For now, We made a hack workaround solution by hiding the front card when the card fliped.

**Comment by AaronCCWong** [comment]
Is this still an issue? If it is can you provide a minimal reproducible example?

**Comment by hamed-musallam** [comment]
@AaronCCWong 

Here you can find a small example, the problem becomes visible if you style your component
```js
containerStyle={{ overflow: "hidden"}}
```
https://codesandbox.io/s/react-flip-bug-f6in2?file=/src/App.js

**Comment by AaronCCWong** [comment]
Can you explain what the intended functionality is?

**Comment by hamed-musallam** [comment]
@AaronCCWong 

we have two cases:
1-  Canvas is still visible even if we don't use ``` overflow: "hidden" ```.
2-  table with ticket header, I need to prevent scroll to be active even if the content if the div is overflow.
      the problem is still the same even if I move the overflow CSS property to the parent component, for example
      `<div style={{overflow:'hidden'}}>
         <ReactCardFlip></ReactCardFlip>
      </div>`

**Comment by AaronCCWong** [comment]
Pushed v1.1.5 which reverts the change causing this issue. Please reopen if that does not fix the issue.

**Comment by hamed-musallam** [comment]
unfortunately, the issue still exists.

https://codesandbox.io/s/react-flip-bug-forked-1cpem?file=/src/App.js

**Comment by mehmetcinarpro** [comment]
We have the same issue. We updated to v1.1.5 but the problem persists..
Thanks for your help

**Comment by hamed-musallam** [comment]
@AaronCCWong 

Any Update?. This bug  still exists and it is going to be very nice if you solve it soon ...
