### ISSUE TITLE
Use prop-types package

### ISSUE THREAD

**Issue by wilomgfx** [AaronCCWong/react-card-flip#8]
React.PropTypes is deprecated as of React v15.5.

use https://www.npmjs.com/package/prop-types

to avoid errors like this 

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by lotusms** [comment]
Yes, I'm having the same issue. Looking into it. This has something to offer [https://facebook.github.io/react/warnings/dont-call-proptypes.html](https://facebook.github.io/react/warnings/dont-call-proptypes.html)

Just not sure how ...rest will go into play here. It'd be nice to have the code modified to fix this warning.

**Comment by wilomgfx** [comment]
I'll send a PR with the changes this weekend.

**Comment by lotusms** [comment]
+1

**Comment by AaronCCWong** [comment]
Sounds good. I will CR asap.
