### ISSUE TITLE
Latest update has broken our solution in Chrome

### ISSUE THREAD

**Issue by taeuscherpferd** [AaronCCWong/react-card-flip#83]
After the latest update, after flipping a tile, the back of the tile is no longer interactable. This only happens in Chrome as far as I can tell. It also seems to have slowed down all of the other animations in our solution. We have downgraded the package to fix, and will probably stay on the downgraded version for the foreseeable future, but I just thought that you should be aware. 👍

**Comment by Sairav** [comment]
Same for me , I am using TextField as the second child (the element that shows up on flip) , it is not interactable.
On hover on the input field of the TextField , mouse pointer doesn't change to cursor, and it is not editable at all . I have also downgraded it.

**Comment by rafaelchampria** [comment]
Same for me, downgraded to 1.1.3 which fixed the issued. My "Back card" is a form with several inputs and buttons

**Comment by sTsaturian** [comment]
Doesn't work for me either. Here is an example: https://codesandbox.io/s/basictextfields-material-demo-forked-7zf38?file=/demo.tsx

**Comment by AaronCCWong** [comment]
Pushed v1.1.5 which reverts the change causing this issue. Please reopen if that does not fix the issue.

**Comment by AaronCCWong** [comment]
Pushed v1.1.5 which reverts the change causing this issue. Please reopen if that does not fix the issue.
